import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='bg-gray-900 text-white'>
        <div className="container mx-auto py-6 px-4">
          <div className="flex justify-between items-center">
            <nav className=''>
              <Link className='px-3' href="/">KINFLKS</Link>
              <Link className='px-3' href="/about">About</Link>
              <Link className='px-3' href="/hair-care-101">Hair Care 101</Link>
              <Link className='px-3' href="/ask-the-professionals">Ask The Professionals</Link>
              <Link className='px-3' href="/insight">Insight</Link>
            </nav>
          </div>
        </div>
      </header>
        {children}
      </body>
    </html>
  );
}
